cache: bundler

language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - jruby-19mode
  - jruby-head
  - rbx-2
  - ruby-head

sudo: false

env:
  - JRUBY_OPTS="-Xcli.debug=true --debug"

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: rbx-2
    - rvm: ruby-head
  fast_finish: true
